### ISSUE TITLE
Is there any way to reorder spaces 

### ISSUE THREAD

**Issue by snowe2010** [asmagill/hs._asm.undocumented.spaces#11]
I'm trying to set up a system that resets all my layout, I usually have 4 spaces and a 5th full screen app (spotify) on the very far right. When I remove the spaces to recreate them, and then create 3 new ones (can't remove the active space or full screen app), the full screen app is now second in the order. I'd like to make it last. Any way to do that?

**Comment by asmagill** [comment]
To my knowledge, no, but it has been quite some time since I've looked for any updates to the general knowledge of the relevant undocumented APIs.  I'll leave this open as a reminder to check again every so often, but I don't have any specific ideas or expectations, just maybe a vague hope that Apple might one day relent and make this easy  :-)

**Comment by asmagill** [comment]
This module is no longer being maintained and will be archived soon. You should check out https://github.com/asmagill/hs._asm.spaces which will (hopefully) soon be added to Hammerspoon itself as `hs.spaces`.

If you do decide to try out the newer version, please let me know if the problem persists and post an issue there so I can look into more closely.

Thanks!
