### ISSUE TITLE
changeToSpace black screen

### ISSUE THREAD

**Issue by Donkeyfish87** [asmagill/hs._asm.undocumented.spaces#12]
When I try to use the changeToSpace function, sometimes the screen blacks out. It only lasts for a short time. Unless I accidentally try to change to the active space, in which case the entire screen goes black until I toggle mission control to switch spaces back and forth once.

**Comment by asmagill** [comment]
This is caused because `changeToSpace` executes the terminal command "killall Dock" after execution to force Mission Control to update to the new state (in this case that you've changed spaces; this is also required when adding or removing a space and also happens for these functions as well). So far, I have not been able to come up with a way to force the updating of state without restarting the Dock process.  If you are aware of open source software which can make these adjustments without restarting the Dock, please post a link -- I'd love to come up with a cleaner solution then what is currently in place here.
