### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by tejasmanohar** [asmagill/hs._asm.undocumented.spaces#13]
Heyo! Does this still work / is it in use? I was having quite a bit of trouble with these APIs on Sierra and beyond.

**Comment by asmagill** [comment]
I have been using it for basic queries with https://github.com/asmagill/hammerspoon-config/blob/master/utils/_actions/dots.lua since Yosemite (I'm on High Sierra now) but I admit I haven't really played with the rest of it in quite some time.

It never did cleanly switch or create spaces without requiring the Dock to be killed, which causes an ugly flash of the screen, so I generally try not to use it very much.

**Comment by tejasmanohar** [comment]
Ah, I see. I was referring to the switching part. I think I may automate keyboard shortcuts :-)

**Comment by tejasmanohar** [comment]
Ah, I see. I was referring to the switching part. I think I may automate keyboard shortcuts :-)
