### ISSUE TITLE
allWindowsForSpace() closes an open context menu

### ISSUE THREAD

**Issue by lucivpav** [asmagill/hs._asm.undocumented.spaces#16]
Steps to reproduce:

1. Open any context menu, e.g. right clicking on desktop
2. Call `allWindowsForSpace()` for a space different from the currently active space
3. **Observe the context menu was closed**

**Comment by asmagill** [comment]
There is nothing we can do to prevent this: The `allWindowsForSpace` function works by locking the screen's display, then iterating through all of the spaces for that screen, capturing window IDs along the way, then returns to your original space and re-enabling the display of changes. 

Because Apple doesn't give us a clean API to access spaces, we have to rely on hacks like this... this has been the status quo since as long as spaces have existed in macOS and isn't likely to change any time soon.
