### ISSUE TITLE
problem with removeSpace()

### ISSUE THREAD

**Issue by yoavg** [asmagill/hs._asm.undocumented.spaces#5]
I'm not sure what is the cause of this, but as of an hour ago I keep observing the following behavior (the same did work before, I guess something changed in the OS state since then).

In the console:

```
> sp.removeSpace(sp.createSpace())
...s/yogo/.hammerspoon/hs/_asm/undocumented/spaces/init.lua:371: ERROR: incorrect type 'no value' for argument 1
```

and also:

```
> x=sp.createSpace()

> x
2808

> sp.removeSpace(x)
...s/yogo/.hammerspoon/hs/_asm/undocumented/spaces/init.lua:371: ERROR: incorrect type 'no value' for argument 1

> x
2808

> sp.removeSpace(2808)
...s/yogo/.hammerspoon/hs/_asm/undocumented/spaces/init.lua:371: ERROR: incorrect type 'no value' for argument 1
```

The space IS created, and I can see it in mission control and in TotalSpaces2. After removing the space using TotalSpaces2's UI, I get:

```
> sp.removeSpace(2808)
removeSpace:must be user-created or fullscreen application space

```

**Comment by asmagill** [comment]
The error on line 371 is caused by windows which do not have an ID.  I'm not sure what types of windows these would be, but I do recall some discussions when hs.window.filter was being developed about the fact that they do exist.

I've added guards in the repository version so that such windows no longer cause the code to break, but I'm not sure what the implications of this are yet, as it's a little hard to test without knowing how to generate a window without id reliably... I'll have to look into it.

You can grab the init.lua file and replace it wherever your module is installed -- init.lua is the only file that has changed.  I'll update the pre-compiled version probably tonight.

As for the last item, removing a space already removed by another method, this is expected -- the id of a space which has been removed will still be accepted by many functions as "valid", but its type will no longer be that of a user space, so this is how we check to see if it is an acceptable space to try and remove.

**Comment by yoavg** [comment]
Thanks (as usual!) for the speedy answer :)

Re the last item -- I just put it there to demonstrate that it IS possible to remove the space, and that the removal of the space does affect the result of the method call.
