### ISSUE TITLE
Problems with multiple displays

### ISSUE THREAD

**Issue by shlomiv** [asmagill/hs._asm.undocumented.spaces#7]
Hey,
When having multiple displays, `spaces.currentSpace()` seems to always return a single number (the maximum space number), and it returns the same number no matter what screen/space i am in.

Also, invoking `spaces.moveToSpace("1")`, for example, makes the external display to turn black until I try to change space in these displays using the pad.

I know that `moveToSpace` should not be used in favor of `changeToDisplay`, however, the binary hosted here doesnt have that function and I cant compile from source..

Big Thanks!
Shlomi

**Comment by asmagill** [comment]
`spaces.currentSpace()` only returns 1 number -- that's one of the reasons its in the legacy/deprecated section (see https://github.com/asmagill/hs._asm.undocumented.spaces#legacy-functions).

`spaces.moveToSpace()` also only works (when it works) with one monitor... it was never designed to work with multi-monitor setups -- again, the reason for this new module and the new functions.

When you say "the binary hosted here", to what are you referring?  The binaries in the releases tab of this repository support all of the listed functions; however, if you have installed them over an old installation of the previous versions of the module, you will need to fully quit and restart Hammerspoon before the new one is recognized -- Hammerspoon (in fact most OS X applications) can't unload shared libraries once an application has started (well, technically they can, but the OS X dynamic library API goes out of its way to make it difficult to do because you can almost never be 100% certain that every reference to the old version is nil before unloading; Apple decided it was better to require a restart of the Application then to have dangling pointers just waiting for a crash.)

**Comment by shlomiv** [comment]
Thanks for replying! 

You are right, for some reason (which I cannot reproduce now), I only found the `Initial Binary Release` before.. I am seeing all of them now and feeling slightly ridiculous :)

Ill try things again with the new version, closing this issue.
Thanks a lot :)
